name: Weekly Banking Scraper

on:
  schedule:
    # Запуск каждый понедельник в 09:00 по Гринвичу (UTC)
    - cron: '0 9 * * 1'
  workflow_dispatch: # Добавляет кнопку ручного запуска в интерфейсе

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install google-play-scraper itunes-app-scraper-dmi pandas matplotlib requests numpy

    - name: Запуск парсера
      run: python parse_banks.py

    - name: Сохранение результатов в репозиторий
      run: |
        git config --global user.name 'Weekly BI Bot'
        git config --global user.email 'bot@github.com'
        git add banking_apps_history.csv dashboard_*.png
        git commit -m "Автоматическое обновление данных: $(date +'%Y-%m-%d')" || exit 0
        git push
